project_id = "qihpywleopgrlvwcffvy"

[functions.stripe-webhook]
verify_jwt = false

[functions.scan-website]
verify_jwt = false

[functions.generate-article]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.test-cms-connection]
verify_jwt = false

[functions.fetch-keywords]
verify_jwt = true

[functions.generate-missing-images]
verify_jwt = false

[functions.publish-to-cms]
verify_jwt = false

[functions.extract-post-keywords]
verify_jwt = false

[functions.fetch-seo-data]
verify_jwt = false
